### ISSUE TITLE
Tools in third-party dir cannot execute

### ISSUE THREAD

**Issue by Dongnini** [scharch/zap#1]
Excellent works! Thanks for sharing and updating.
The issue is that, when I tried the updated SONAR, the tools in third-party dir cannot execute, including muscle and vsearch. I haven't tried others till now. Maybe the problem is that, I am using MacOS but the tools are in binary code.
The Error looks like: 'Bio.Application.ApplicationError: Non-zero return code 126 from './sonar/third-party/muscle -in ****N3/work/lineage/align/align000001_temp.fa -out ****N3/work/lineage/align/align000001_temp.aln', message '/bin/sh: ./sonar/third-party/muscle: cannot execute binary file' and 'OSError: [Errno 8] Exec format error: './sonar/third-party/vsearch'

I can find muscle for MacOS from elsewhere and replace the file in third-party dir, but I can't find 'vsearch'. Would you please tell where is the third-party tool vsearch for MacOS, or add tools in the new version of sonar?

By the way, it cause problems after the dir name 'sonar' was changed to 'SONAR'. Every time using 'import sonar', it can not find the module called sonar. It can be fixed when I changed the dir name back.
Thanks for your great work!

**Comment by shengzizhang** [comment]
You could download Vsearch source code in github and compile it in MacOS.

Best,

Zizhang

**Comment by scharch** [comment]
Thanks. I am aware of the SONAR/sonar bug and will try to push out a fix
soon. I am also to include executables compiled for MacOS. Timeframe for
both is probably a couple of weeks because, life.

**Comment by scharch** [comment]
These bugs are now fixed in v4 (specifically, commits `00e75fb` and `9389175`). Please pull/clone the latest code and rerun `setup.py`. Sorry for the long wait.
