### ISSUE TITLE
X11 error

### ISSUE THREAD

**Issue by wangsiling123** [scharch/zap#10]
When operate the code "sonar get_island output/tables/cap256-week34H_goodVJ_unique_id-div.tab --mab CAP256-VRC26.01 --mab CAP256-VRC26.08", error is displayed as below. I run docker as "docker run -it -e DISPLAY=$DISPLAY -v ~:/host/home scharch/sonar". 

Loading required package: misc3d
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  :
  unable to start device X11
Calls: getIsland -> X11
In addition: Warning message:
In X11(type = "Xlib", family = "misc") :
  unable to open connection to X11 display ''

**Comment by scharch** [comment]
Can you please check the value of `$DISPLAY` on your local machine (ie prior to initiating Docker)?

**Comment by wangsiling123** [comment]
Dear Chaim:
Thanks for your write back. This question has been solved by using Mobaxterm to connect server. Moreover, conld you send me the antibody heavy and light chain germline library of mouse ? I plan to sequence mouse BCR sequence. Your help would be greatly appreciated.
Looking forward to hearing from you.


Sincerely
Siling Wang
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scharch/SONAR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 凌晨0:12
收件人:&nbsp;"scharch/SONAR"<SONAR@noreply.github.com&gt;;
抄送:&nbsp;"走向你的未来"<547451251@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [scharch/SONAR] X11 error (#10)





 
Can you please check the value of $DISPLAY on your local machine (ie prior to initiating Docker)?

**Comment by scharch** [comment]
I am glad you were able to get it working.

For mouse germline databases, you could consider starting with [IMGT](http://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Mus_musculus/IG/). However, it would probably be best to curate it for the specific strain you are working with. See [this paper](https://onlinelibrary.wiley.com/doi/abs/10.1111/imcb.12288) for more details.

**Comment by wangsiling123** [comment]
Thanks for your help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scharch/SONAR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 晚上11:34
收件人:&nbsp;"scharch/SONAR"<SONAR@noreply.github.com&gt;;
抄送:&nbsp;"走向你的未来"<547451251@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [scharch/SONAR] X11 error (#10)





 
I am glad you were able to get it working.
 
For mouse germline databases, you could consider starting with IMGT. However, it would probably be best to curate it for the specific strain you are working with. See this paper for more details.
