### ISSUE TITLE
Cluster number for each sequence id

### ISSUE THREAD

**Issue by NikaAb** [scharch/zap#11]
Dear SONAR team,
After running the  "cluster_Sequences" command, where can I find the corresponding cluster number for each sequence id?
Thanks!

**Comment by scharch** [comment]
Hi @NikaAb 
SONAR does not assign cluster numbers. Instead, it uses the `sequence_id` of the centroid for each cluster. This is recorded in the `centroid` column of the updated rearrangements TSV under `output/tables`. This information is not preserved in the fasta-format output, so if you are running `1.4-cluster_sequences.py` outside of the full pipeline, you will have to extract it from the `vsearch` output saved as `<input>.cluster`.

**Comment by NikaAb** [comment]
Dear @scharch 
Thanks for your answer. It helped me a lot.
