### ISSUE TITLE
error in blastn output format 

### ISSUE THREAD

**Issue by madisonberry** [scharch/zap#13]
I'm trying to run blast_V on a dataset and I'm getting this error. It looks like the outfmt isn't specified correctly. 

Thu Feb 18 10:38:07 2021 -- SONAR v4.2-40-g9931941-dirty run with command:
	/SONAR/annotate/1.1-blast_V.py --fasta heavies.fasta --locus H --derep --species rhesus -f

vsearch v2.8.1_linux_x86_64, 340.2GB RAM, 40 cores
https://github.com/torognes/vsearch

Reading file /datacommons/dhvi/mb488/SONAR/test/RM10N011/work/internal/tempForDerep.fa 100%  
1261706 nt in 2078 seqs, min 303, max 1002, avg 607
Dereplicating 100%  
Sorting 100%
2078 unique sequences, avg cluster 1.0, median 1, max 1
Writing output file 100%  
Writing uc file, first part 100%  
Writing uc file, second part 100%  
TOTAL: 2078 processed, 1061 good
Starting blast of /datacommons/dhvi/mb488/SONAR/test/RM10N011/work/annotate/vgene/RM10N011_001.fasta against /SONAR/germDB/IgHV_BU_DD.fasta...
Traceback (most recent call last):
  File "/SONAR/annotate/__init__.py", line 35, in blastProcess
    cline()
  File "/hpc/home/mb488/.local/lib/python3.6/site-packages/Bio/Application/__init__.py", line 569, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from '/SONAR/third-party/blastn_linux64 -out /datacommons/dhvi/mb488/SONAR/test/RM10N011/work/annotate/vgene/RM10N011_001.txt -outfmt "\'6 qseqid sseqid pident length mismatch gaps qstart qend sstart send evalue bitscore sstrand\'" -query /datacommons/dhvi/mb488/SONAR/test/RM10N011/work/annotate/vgene/RM10N011_001.fasta -db /SONAR/germDB/IgHV_BU_DD.fasta -evalue 0.001 -word_size 7 -max_target_seqs 10 -gapopen 5 -gapextend 2 -penalty -1 -reward 1', message "BLAST query/options error: ''6' is not a valid output format"

**Comment by scharch** [comment]
@madisonberry did you mean to close the issue? Were you able to solve the problem?

**Comment by madisonberry** [comment]
I saw that another issue addressed this (FYI: Biopython 1.74 breaks backwards compatibility in NcbiblastnCommandline). It seems that if I remove the single quotes it should work fine but I am new to docker/images and I am not sure how to make this change. What would be the best way to go about fixing this?

**Comment by scharch** [comment]
Should work in Docker, please let me know if not.
For local usage, you can manually edit this line (and similar lines immediately following)
https://github.com/scharch/SONAR/blob/52ecec53481c5bea3191f3af11e5687fe197a1c5/annotate/__init__.py#L17
to remove the `\'`s.

**Comment by madisonberry** [comment]
I’m using docker and it’s not working.

**Comment by scharch** [comment]
Can you please post the command you are using to start Docker? I notice in the output that you posted that it looks like you are getting Biopython from a local install:

> Traceback (most recent call last):
> File "/SONAR/annotate/**init**.py", line 35, in blastProcess
> cline()
> File "**/hpc/home/mb488/**.local/lib/python3.6/site-packages/Bio/Application/**init**.py", line 569, in **call**
> raise ApplicationError(return_code, str(self), stdout_str, stderr_str)

**Comment by madisonberry** [comment]
I'm actually using singularity. 

singularity run --bind /datacommons/dhvi/mb488 /datacommons/dhvi/mb488/bin/sonar_latest.sif

**Comment by scharch** [comment]
OK, I'm not familiar with singularity, but if you are using a local Biopython install you either need to edit the SONAR source code as indicated above or perhaps create a new conda environment with specifically version 1.73 of Biopython to use for SONAR.
