### ISSUE TITLE
id-div script now looks for project tree dir before it's defined

### ISSUE THREAD

**Issue by ressy** [scharch/zap#17]
Small bug I think introduced in c8c19f2606c55e7d7dd8db76976a1f3ec3374028: If I now call `sonar id-div` with neither `-g` nor `--species` given, it looks for the gene_locus file, but does so before defining the project dir farther down the script.

```
Traceback (most recent call last):
  File "/SONAR/lineage/2.1-calculate_id-div.py", line 328, in <module>
    if os.path.exists(f"{prj_tree.internal}/gene_locus.txt"):
NameError: name 'prj_tree' is not defined
```

 I think you can probably just shift that assignment around to fix it.

**Comment by ressy** [comment]
No wait, there's at least one more hiccup: it tries to use `arguments['--species']` in that new block even though it's `None`.  I'll try to propose a change tomorrow and you can see if it makes sense.

**Comment by scharch** [comment]
Ugh, sloppy sloppy sloppy, sorry.
Should be fixed now.

**Comment by ressy** [comment]
No worries and thanks!
