### ISSUE TITLE
cp sonar ~/bin. No such file

### ISSUE THREAD

**Issue by HuiwuZhao** [scharch/zap#2]
Excellent work. I was trying to run it locally in my Mac OS10.14.5

Following the installation instructions, when I ran
cp sonar ~/bin
It showed
cp: sonar: No such file or directory

Could you please help me? Thanks.

**Comment by scharch** [comment]
Did you get an error running the setup? Please run `setup.py` again and paste the output here.

**Comment by scharch** [comment]
closing as stale
