### ISSUE TITLE
FYI: Biopython 1.74 breaks backwards compatibility in NcbiblastnCommandline

### ISSUE THREAD

**Issue by ressy** [scharch/zap#4]
This is more just a heads up than a request/bug report.  I found that the blastn steps fail when I have the newest Biopython installed, apparently because they changed how arguments to NcbiblastnCommandline are parsed.  If I have version 1.74, I need to remove the extra single quotes wrapping the `outfmt` string in `blastProcess` to make it work.  With 1.73 or earlier (looks like 1.69 in a SONAR docker container?) it works as-is, though.

https://github.com/biopython/biopython/issues/2055
https://github.com/biopython/biopython/pull/2071

**Comment by scharch** [comment]
Good to know, thanks

**Comment by scharch** [comment]
Oddly, this appears to be working now (Biopython 1.79) though looking at the code I don't understand why. In any case, can be fixed for all versions by using `'"outfmt string"'` instead of `"\'outfmt string\'"`, will push a fix shortly
