### ISSUE TITLE
igphyml wrapper crashes when given custom V library

### ISSUE THREAD

**Issue by ressy** [scharch/zap#5]
I get this exception when trying to use the `--lib` option to `sonar igphyml`:

    Traceback (most recent call last):
      File "/SONAR/phylogeny/3.2-run_IgPhyML.py", line 358, in <module>
        if not os.path.isfile(arguments['-lib']):
    KeyError: '-lib'

I think there's a missing second dash in a few places for the lib argument:

    if arguments['--lib'] is not None:
        if not os.path.isfile(arguments['-lib']):
            sys.exit("Can't find germline file %s" % argument['-lib'])

It works if I replace that with:

    if arguments['--lib'] is not None:
        if not os.path.isfile(arguments['--lib']):
            sys.exit("Can't find germline file %s" % argument['--lib'])

(This is in https://github.com/scharch/SONAR/blob/master/phylogeny/3.2-run_IgPhyML.py#L365)

**Comment by scharch** [comment]
Yeah, sorry about that. Fixed in commit `4625c29`

**Comment by ressy** [comment]
Thanks!
