### ISSUE TITLE
No identity/divergence plot file with only one antibody selected

### ISSUE THREAD

**Issue by ressy** [scharch/zap#9]
I noticed I wasn't getting the islandSeqs.png output for a particular id-div.tab file and tracked it down to the fact that there's only one antibody column in the input file.  If I use a table with multiple antibody columns but only select one, the plot image also isn't saved.  It looks like this is because [plotting the final selections is skipped if there's only one antibody](https://github.com/scharch/SONAR/blob/master/lineage/2.2-get_island_interactive.R#L297) and that part includes the ggsave call to save the image.  Is that behavior intentional?  If I disable the check I get a png with just the one plot, which seems to work fine.

**Comment by scharch** [comment]
Yeah, the plotting feature was originally designed with the [VRC01 lineage](https://www.cell.com/cell/fulltext/S0092-8674(15)00257-) in mind, to allow me to review how many of the selected reads were coming from each anchor antibody/sub-lineage. I guess it never seemed necessary for a single anchor...
I will make a note to take that check out at some point, probably with version 4.3 in the next month or so.

**Comment by ressy** [comment]
Thanks!
